name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]


jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Rebuilding website
      run: npx --package mini-cross@0.15.2 mc --no-tty _ ./build.sh

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.

